### ISSUE TITLE
Σύνδεσμος που δεν λειτουργεί

### ISSUE THREAD

**Issue by gpapadop79** [sonic2000gr/diktia#1]
Ο σύνδεσμος στην σελίδα 69 για Συνοπτική Μεθοδολογία Ασκήσεων IP Fragmentation  δεν λειτουργεί.
http://www.freebsdworld.gr/diktia/ipfragmentation.pdf

Εξαιρετική δουλειά συνάδελφε....!!!!

**Comment by sonic2000gr** [comment]
Ναι γιατί αυτό το site δεν υφίσταται πλέον... Αλλά το αρχείο μπορεί να βρεθει εδώ:
http://schoolspace.gr/diktia/ipfragmentation.pdf
Σε ευχαριστώ για το σχόλιο και τα καλά σου λόγια!
